### ISSUE TITLE
Running on arm64 (Pinebook Pro)

### ISSUE THREAD

**Issue by loplkc** [stargatedaw/stargate#1]
The program does not run when built on a Pinebook Pro. There are a variety of possible causes: it could be a lack of support and/or testing, a missing dependency I could not find, or something else, and I am not knowledgeable enough to figure out which it is.
The program appears to build successfully, even when some dependencies were missing. However, when I try to run it, it gives an error regarding pyqt5 (more information in log file). When I tried to use the Fedora script to find out what packages I needed to install, I installed as many of the dependencies as I could find in the Arch Linux ARM repository, but the same issue occurred.
If this is a support issue, I would greatly appreciate if arm64 became a supported platform for Stargate. Pine64 devices are pitifully weak but portable and efficient Linux machines, and I think Stargate would be a perfect fit for them (if it wouldn't be too much trouble to maintain).

Log file (attempt to call the binary stargate first, then the script):
```
[2021-09-29 22:46:35,734] INFO /usr/local/bin/stargate       : 52 - sys.argv == ['/usr/local/bin/stargate']
[2021-09-29 22:46:35,754] INFO /usr/local/lib/stargate/stargate/sgui/sgqt.py: 19 - Using PyQt5
[2021-09-29 22:46:35,779] ERROR /usr/local/lib/stargate/stargate/sglib/log.py: 62 - Traceback (most recent call last):

  File "/usr/local/bin/stargate", line 88, in main
    start_stargate(args.project_file)

  File "/usr/local/bin/stargate", line 50, in start_stargate
    from sglib.log import LOG, setup_logging

ModuleNotFoundError: No module named 'sglib'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/local/bin/stargate", line 107, in <module>
    main()

  File "/usr/local/bin/stargate", line 104, in main
    start_stargate(args.project_file)

  File "/usr/local/bin/stargate", line 53, in start_stargate
    from sgui.sgqt import QApplication, QGuiApplication, QtCore

  File "/usr/local/lib/stargate/stargate/sgui/sgqt.py", line 21, in <module>
    from PyQt5 import QtGui, QtWidgets, QtCore

ImportError: /usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: _ZTI18QOpenGLTimeMonitor, version Qt_5

[2021-09-29 22:47:34,457] INFO /home/axel/git/stargate/src/scripts/stargate: 52 - sys.argv == ['scripts/stargate']
[2021-09-29 22:47:34,475] INFO /home/axel/git/stargate/src/sgui/sgqt.py: 19 - Using PyQt5
[2021-09-29 22:47:34,500] INFO /home/axel/git/stargate/src/scripts/stargate: 52 - sys.argv == ['scripts/stargate']
[2021-09-29 22:47:34,500] INFO /home/axel/git/stargate/src/scripts/stargate: 52 - sys.argv == ['scripts/stargate']
[2021-09-29 22:47:34,502] INFO /home/axel/git/stargate/src/sgui/sgqt.py: 19 - Using PyQt5
[2021-09-29 22:47:34,502] INFO /home/axel/git/stargate/src/sgui/sgqt.py: 19 - Using PyQt5
[2021-09-29 22:47:34,528] ERROR /home/axel/git/stargate/src/sglib/log.py: 62 - Traceback (most recent call last):

  File "/home/axel/git/stargate/src/scripts/stargate", line 88, in main
    start_stargate(args.project_file)

  File "/home/axel/git/stargate/src/scripts/stargate", line 53, in start_stargate
    from sgui.sgqt import QApplication, QGuiApplication, QtCore

  File "/home/axel/git/stargate/src/sgui/sgqt.py", line 21, in <module>
    from PyQt5 import QtGui, QtWidgets, QtCore

ImportError: /usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: _ZTI18QOpenGLTimeMonitor, version Qt_5


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/axel/git/stargate/src/scripts/stargate", line 107, in <module>
    main()

  File "/home/axel/git/stargate/src/scripts/stargate", line 104, in main
    start_stargate(args.project_file)

  File "/home/axel/git/stargate/src/scripts/stargate", line 53, in start_stargate
    from sgui.sgqt import QApplication, QGuiApplication, QtCore

  File "/home/axel/git/stargate/src/sgui/sgqt.py", line 21, in <module>
    from PyQt5 import QtGui, QtWidgets, QtCore

ImportError: /usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: _ZTI18QOpenGLTimeMonitor, version Qt_5

[2021-09-29 22:47:34,528] ERROR /home/axel/git/stargate/src/sglib/log.py: 62 - Traceback (most recent call last):

  File "/home/axel/git/stargate/src/scripts/stargate", line 88, in main
    start_stargate(args.project_file)

  File "/home/axel/git/stargate/src/scripts/stargate", line 53, in start_stargate
    from sgui.sgqt import QApplication, QGuiApplication, QtCore

  File "/home/axel/git/stargate/src/sgui/sgqt.py", line 21, in <module>
    from PyQt5 import QtGui, QtWidgets, QtCore

ImportError: /usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: _ZTI18QOpenGLTimeMonitor, version Qt_5


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/axel/git/stargate/src/scripts/stargate", line 107, in <module>
    main()

  File "/home/axel/git/stargate/src/scripts/stargate", line 104, in main
    start_stargate(args.project_file)

  File "/home/axel/git/stargate/src/scripts/stargate", line 53, in start_stargate
    from sgui.sgqt import QApplication, QGuiApplication, QtCore

  File "/home/axel/git/stargate/src/sgui/sgqt.py", line 21, in <module>
    from PyQt5 import QtGui, QtWidgets, QtCore

ImportError: /usr/lib/python3.9/site-packages/PyQt5/QtGui.abi3.so: undefined symbol: _ZTI18QOpenGLTimeMonitor, version Qt_5
```

**Comment by ghost** [comment]
Hello, thanks for reporting.  Stargate has first-tier support for ARM platforms, but I have only tested it on Raspberry Pi4 and a 2015 era oDroid, using Raspbian, Ubuntu and Fedora.  This appears to be an issue with the PyQt packages that your distro provided, that they will need to fix.  But I will help as much as possible.

# First
Try running this from the command line:
```
python3
>>> from PyQt5 import QtGui, QtWidgets, QtCore
```
I assume you will see the same error.  If so, file a bug report with your distro, they will need to fix the package

# Potential work-arounds
## Install PyQt from pip
```
python3 -m pip install PyQt5
# Or
python3 -m pip install PyQt6
```
## Upgrade Python
Check your version
```
python3 -V
```
If it is an older version, or a very new version, try installing 3.8, 3.9 if possible

If you have multiple version of python installed, you can select them like this:
```
python3.7 $(which stargate)
python3.9 $(which stargate)
```

## Try another distro
As previously mentioned, Stargate is known to work on ARM64 Ubuntu, Debian and Fedora, there is no reason to believe it would not work on a Pinebook.

**Comment by ghost** [comment]
@loplkc , Also feel free to chat with us on [Discord](https://discord.gg/7mP5psUN7D), might be easier to assist.

**Comment by ghost** [comment]
Have not heard back from you, and this is almost certainly an issue with your distro, so closing the ticket.  Feel free to discuss further with us in Discord, we are eager to know if Stargate works on Pinebook.
