### ISSUE TITLE
It fails to start on OpenSUSE Leap 15.3

### ISSUE THREAD

**Issue by ghost** [stargatedaw/stargate#22]
Hi,

Very interesting project. However, I could not install it. I'm using OpenSUSE Leap 15.3.

Adding PYTHONPATH /usr
Did not detect local development environment, trying system installation
Adding PYTHONPATH /usr/share/stargate/stargate
[2021-11-10 13:37:24,285] INFO /usr/bin/stargate             : 72 - sys.argv == ['/usr/bin/stargate']
[2021-11-10 13:37:24,286] ERROR /usr/share/stargate/stargate/sglib/log.py: 90 - Traceback (most recent call last):

  File "/usr/share/stargate/stargate/sgui/sgqt.py", line 7, in <module>
    import PyQt6

ModuleNotFoundError: No module named 'PyQt6'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/usr/bin/stargate", line 155, in <module>
    main()

  File "/usr/bin/stargate", line 152, in main
    start_stargate(args.project_file)

  File "/usr/bin/stargate", line 91, in start_stargate
    app, scaler = _setup()

  File "/usr/bin/stargate", line 73, in _setup
    from sgui.sgqt import QApplication, QGuiApplication, QtCore

  File "/usr/share/stargate/stargate/sgui/sgqt.py", line 11, in <module>
    import PyQt5

ModuleNotFoundError: No module named 'PyQt5'

--------

I don't think OpenSUSE has PyQt6 in their repos.

hp:~ # hwinfo --short
cpu:                                                            
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1084 MHz
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1311 MHz
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1380 MHz
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1505 MHz
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1825 MHz
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 2016 MHz
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 2050 MHz
                       Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz, 1925 MHz
keyboard:
  /dev/input/event0    AT Translated Set 2 keyboard
  /dev/input/event20   MX Anywhere 2 Keyboard
mouse:
  /dev/input/mice      ETPS/2 Elantech Touchpad
  /dev/input/mice      MX Anywhere 2 Mouse
joystick:
  /dev/input/event8    ST LIS3LV02DL Accelerometer
monitor:
                       LCD Monitor
graphics card:
                       nVidia GP108M [GeForce MX150]
                       Intel UHD Graphics 620 (Whiskey Lake)
sound:
                       Intel Cannon Point-LP High Definition Audio Controller
storage:
                       Intel 82801 Mobile SATA Controller [RAID mode]
network:
  wlan0                Intel Cannon Point-LP CNVi [Wireless-AC]
  eth0                 Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller
network interface:
  lo                   Loopback network interface
  eth0                 Ethernet network interface
  wlan0                WLAN network interface
disk:
  /dev/sda             Samsung SSD 860
partition:
  /dev/sda1            Partition
  /dev/sda2            Partition
  /dev/sda3            Partition
usb controller:
                       Intel Cannon Point-LP USB 3.1 xHCI Controller
bios:
                       BIOS
bridge:
                       Intel Cannon Point-LP PCI Express Root Port #1
                       Intel Cannon Point-LP LPC Controller
                       Intel Cannon Point-LP PCI Express Root Port #10
                       Intel Coffee Lake HOST and DRAM Controller
                       Intel Cannon Point-LP PCI Express Root Port #9
                       Intel Cannon Point-LP PCI Express Root Port #5
hub:
                       Linux Foundation 2.0 root hub
                       Linux Foundation 3.0 root hub
memory:
                       Main Memory
bluetooth:
                       Intel Bluetooth Device
unknown:
                       FPU
                       DMA controller
                       PIC
                       Keyboard controller
                       PS/2 Controller
                       Intel Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem
                       Intel Cannon Point-LP MEI Controller #1
                       Intel Cannon Point-LP SPI Controller
                       Intel Cannon Point-LP Serial IO I2C Host Controller
                       Intel Cannon Point-LP Thermal Controller
                       Intel Cannon Point-LP Shared SRAM
                       Intel Cannon Point-LP SMBus Controller
  /dev/input/event12   Lite-On HP Wide Vision FHD Camera

**Comment by ghost** [comment]
Hello,

PyQt6 is not required, Stargate DAW also works with PyQt5, but it appears that is not installed either.  PyQt6 is preferred because it works better with Wayland, which is why you see it first, but PyQt5 is mentioned later in the logs.

These are the dependencies:
https://github.com/stargateaudio/stargate/blob/main/scripts/fedora_deps.sh

**Comment by ghost** [comment]
Ok. Thanks.
